#!/usr/bin/env tsx
// =============================================================================
// Commit selection for the judged task set, Phase 0 — no model calls.
// Spec: docs/specs/2026-09-29-commit-reconstruction-bench.md §4.2 steps 1–3.
//
//   pnpm bench:commits --since <YYYY-MM-DD> [--until <YYYY-MM-DD>] [--out <file>]
//
// `basicFilter` is BuffBench's (freebuff evals/buffbench/pick-commits.ts,
// Apache-2.0) rule for rule, with one deliberate fix: theirs reads stats from
// `git show --stat` and matches the text "files changed", which a single-file
// commit prints as "1 file changed" — so every one-file commit parsed as zero
// files and was dropped. Their own `filesChanged <= 1 && lines < 5` rule shows
// they meant to keep the rest; numstat counts them correctly.
// =============================================================================

import { execFileSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

export interface FileStat {
  path: string;
  added: number;
  deleted: number;
}

export interface CommitInfo {
  sha: string;
  parentSha: string;
  date: string;
  /** Subject line only, as BuffBench's `%s`. */
  message: string;
  files: FileStat[];
  /** A `Co-Authored-By: Claude` trailer — spec §6.3's split. */
  coAuthoredByClaude: boolean;
}

export type App = "core" | "tui";

const RS = "\x1e";
const US = "\x1f";

export function parseLog(raw: string): CommitInfo[] {
  return raw
    .split(RS)
    .filter((chunk) => chunk.trim())
    .map((chunk) => {
      const [sha, parents, date, message, body, rest = ""] = chunk.split(US);
      const files = rest
        .split("\n")
        .filter((line) => line.includes("\t"))
        .map((line) => {
          const [a, d, ...p] = line.split("\t");
          // numstat prints "-" for binary files.
          return { path: p.join("\t"), added: Number(a) || 0, deleted: Number(d) || 0 };
        });
      return {
        sha,
        parentSha: parents.split(" ")[0] ?? "",
        date,
        message,
        files,
        coAuthoredByClaude: /co-authored-by:\s*claude/i.test(body),
      };
    });
}

export function basicFilter(commit: CommitInfo): boolean {
  const m = commit.message.toLowerCase();
  const filesChanged = commit.files.length;
  const lines = commit.files.reduce((n, f) => n + f.added + f.deleted, 0);
  if (
    m.includes("update dependencies") ||
    m.includes("bump ") ||
    (m.includes("upgrade ") && m.includes("version")) ||
    m.includes("auto-generated") ||
    m.includes("generated by") ||
    m.includes("ci:") ||
    m.includes("build:") ||
    (m.includes("format") && m.includes("code")) ||
    m.includes("lint") ||
    m.includes("prettier") ||
    m.startsWith("merge ") ||
    m.startsWith("revert ") ||
    (m.includes("readme") && filesChanged <= 1) ||
    (m.includes("docs:") && filesChanged <= 2)
  ) {
    return false;
  }
  return !(
    filesChanged === 0 ||
    (filesChanged <= 1 && lines < 5) ||
    filesChanged > 50 ||
    lines > 2000
  );
}

/**
 * The app a commit belongs to (spec §4.2 step 3): whichever of apps/core and
 * apps/tui has more non-test changed lines under src/, or undefined when the
 * commit changes neither.
 */
export function appFor(commit: CommitInfo): App | undefined {
  const lines = { core: 0, tui: 0 };
  for (const f of commit.files) {
    const m = /^apps\/(core|tui)\/src\/.*\.tsx?$/.exec(f.path);
    if (!m || /\.test\.tsx?$/.test(f.path)) continue;
    lines[m[1] as App] += f.added + f.deleted;
  }
  if (lines.core === 0 && lines.tui === 0) return undefined;
  return lines.tui > lines.core ? "tui" : "core";
}

export function listCommits(repoDir: string, since: string, until?: string): CommitInfo[] {
  const raw = execFileSync(
    "git",
    [
      "log",
      "--no-merges",
      `--since=${since}`,
      ...(until ? [`--until=${until}`] : []),
      `--format=${RS}%H${US}%P${US}%ad${US}%s${US}%b${US}`,
      "--date=short",
      "--numstat",
    ],
    { cwd: repoDir, encoding: "utf-8", maxBuffer: 256 << 20 },
  );
  // A root commit has no parent to check out, so it cannot be a task.
  return parseLog(raw).filter((c) => c.parentSha);
}

export interface Candidate extends CommitInfo {
  app: App;
}

export function selectCandidates(commits: CommitInfo[]): Candidate[] {
  const out: Candidate[] = [];
  for (const c of commits) {
    if (!basicFilter(c)) continue;
    const app = appFor(c);
    if (app) out.push({ ...c, app });
  }
  return out;
}

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i > 0 ? process.argv[i + 1] : undefined;
}

function main(): void {
  const since = arg("since");
  if (!since) {
    // Spec §4.8: the window's start is the contamination control. No default,
    // because a default would be a silent choice about which model is clean.
    throw new Error("--since <YYYY-MM-DD> is required: the day after the pinned model's release");
  }
  const repo = path.join(import.meta.dirname, "..", "..", "..");
  const all = listCommits(repo, since, arg("until"));
  const candidates = selectCandidates(all);
  const count = (app: App, claude?: boolean) =>
    candidates.filter(
      (c) => c.app === app && (claude === undefined || c.coAuthoredByClaude === claude),
    ).length;

  console.log(`window ${since} → ${arg("until") ?? "HEAD"}`);
  console.log(`  commits scanned        ${all.length}`);
  console.log(`  after basic + scope    ${candidates.length}`);
  for (const app of ["core", "tui"] as const) {
    console.log(
      `    ${app.padEnd(5)} ${String(count(app)).padStart(4)}` +
        `   (Claude co-authored ${count(app, true)}, not ${count(app, false)})`,
    );
  }
  const out = arg("out");
  if (out) {
    fs.mkdirSync(path.dirname(out), { recursive: true });
    // The window travels with the candidates into the task files: it is what
    // the contamination check (spec §4.8) compares a model's release against.
    const window = { since, until: arg("until") ?? null };
    fs.writeFileSync(out, JSON.stringify({ window, candidates }, null, 2));
    console.log(`\n${out}`);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) main();
