import type { MetaRecord } from "nextra";

export default {
  index: "Overview",
  "agent-loop": "Agent loop",
  providers: "Provider layer",
  caching: "Caching",
  tools: "Tool system",
  context: "Context engine",
  bus: "Event bus",
  hooks: "Lifecycle hooks",
  permissions: "Permission engine",
  subagents: "Sub-agent runtime",
  memory: "Memory",
  "knowledge-graph": "Knowledge graph",
  sessions: "Sessions, store & rollout",
  compaction: "Compaction",
  ipc: "IPC protocol",
  runtime: "Effect runtime & DI",
  eval: "Eval harness",
  "cost-efficiency": "Cost efficiency",
  mcp: "MCP client",
  skills: "Skills system",
  cli: "CLI entrypoint & subcommands",
  commands: "Slash commands",
  usage: "Usage accounting",
  "repo-map": "Repo map",
  "claude-sessions": "Claude Code session import",
  "graph-explorer": "Graph explorer addon",
  autonomous: "Autonomous runs"
} satisfies MetaRecord;
