// Shared types — re-exported explicitly to avoid empty export * issues with isolatedModules

// Types
export type {
  Message,
  MessagePart,
  ToolContext,
  ToolResult,
  ToolDef,
  ToolRegistry,
  JsonSchema,
  ToolListItem,
  CommandInfo,
  ProviderInfo,
  ProviderStatus,
  WebCredentialSpec,
  WebCredentials,
  ProviderDefinition,
  SessionConfig,
  EffortLevel,
  SessionInfo,
  SessionStatus,
  SessionMeta,
  SerializedMessage,
  SessionContext,
  SessionResumeResult,
  SessionFilter,
  ClaudeSessionMeta,
  ClaudeTranscript,
  ClaudeListFilter,
  ContextSegmentId,
  ContextSegmentStat,
  ContextBreakdown,
  ModelLimit,
  ModelCost,
  ModelInfo,
  MemoryType,
  MemoryEntry,
  MemoryGraphStats,
  AnthropicAuthMode,
  RedactedConfig,
  TurnResult,
  ExportedSession,
  ShellStatus,
  ShellSummary,
  ShellOutputResult,
  AgentStatus,
  AgentSummary,
  NightRunSummary,
  AgentOutputResult,
} from "./types.js";

// IPC Protocol
export type {
  JsonRpcRequest,
  JsonRpcResponse,
  StreamResponse,
  StreamEvent,
  CacheStats,
  CacheMissSample,
  QuestionSpec,
  PermissionPromptDecision,
  MethodName,
  MethodParams,
  MethodResult,
  ParamType,
} from "./ipc/protocol.js";

export { METHODS, REQUIRED_PARAMS, parseAgentActivity } from "./ipc/protocol.js";
